### ISSUE TITLE
Tutorial SetUp

### ISSUE THREAD

**Issue by PeckySF** [nikeyes/Mantis2Trello#1]
Hi, it would be nice to have a tutorial on the project, in order to know how to setup Mantis2Trello, so we can assign one of our Trello Board and a list to new tracked Mantis.
I tried with the Trello API, but my Mantis tasks do not add up to my chosen List in my chosen trello board.

**Comment by nikeyes** [comment]
Hi PeckySF,

Thanks for your feedback. This is a simple pluggin created to my current company.

I created a mini tutorial to set up the project. 
You can see the mini tutorial in the Readme.md file on the Repository: https://github.com/nikeyes/Mantis2Trello

If this tutorial is not enough to help you to run the plugin, I will need a url's example of a ticket of your Mantis to find if there is any incompatibility with the url .

P.D. you can let blank values for the configuration key: "Trello Id Inmediato Label", "Trello id Urgente Label" and "Trello Id Alta Label". They are specfic keys for our customization of Mantis.

Thanks, 

Jorge

**Comment by nikeyes** [comment]
You can try the plugin with the tickets of the Mantis Web sample: https://www.mantisbt.org/bugs/view.php?id=21147
