### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by henrique-barbase** [nikeyes/Mantis2Trello#3]
Hi, I'm from Brazil, could you make a video of how to configure, because I do not know

**Comment by henrique-barbase** [comment]
@nikeyes Thank you

**Comment by nikeyes** [comment]
Hi Henrique,  I will try to make a video on monday or tuesday.

**Comment by henrique-barbase** [comment]
Thank you very much, I await the link.

**Comment by henrique-barbase** [comment]
Hi, good morning, did you make the video?

I did according to readme and could not install. 

My mantis version is 2.16.0, and not function.

Thank you so much!

**Comment by nikeyes** [comment]
Hi Henrique, 
Sorry for the delay,  i'm out and i will arrive this afternoon.  I will try to make the video tonight. 
Jorge

Enviado desde Yahoo Mail con Android 
 
  El mié., ago. 1, 2018 a 15:13, Henrique de Sousa Barbase<notifications@github.com> escribió:   
Hi, good morning, did you make the video?

I did according to readme and could not install.

Thank you so much!

**Comment by henrique-barbase** [comment]
Thank you

**Comment by nikeyes** [comment]
The video link: https://youtu.be/IEXHEW9P7VA

If you have any problem, you don't hesitate contact with me.

Thanks,

Jorge
