### ISSUE TITLE
Not asking for Trello permissions

### ISSUE THREAD

**Issue by mefiu** [nikeyes/Mantis2Trello#4]
Mantis 2.16.0
Chrome Version 70.0.3538.77 (Official Build) (64-bit)
Windows 10 x64

**Comment by nikeyes** [comment]
Hi mefiu! 

Can you try to remove your cookies? 

Thx!

**Comment by mefiu** [comment]
I've managed to solve it.
The case is you have assumed that 'view.php' is exposed via:
"*://*/mantis/view.php*"
"*://*/bugs/view.php*"
Mine is exposed directly, so I'd to add this:
"*://*/view.php*"
to manifest.json and background.js

**Comment by nikeyes** [comment]
Ohh!  Thank you!!  

Can you make a pull request with this changes? 

Thanks in advance!

**Comment by mefiu** [comment]
I'd like to but I cannot push to this repo :(

**Comment by nikeyes** [comment]
Hi! 
You need to fork the repository and create a Pull Request. It is the way in which Github works with other people's projects. When I get the PullRequest I can approve it and merge it to the repository.

https://help.github.com/articles/creating-a-pull-request/

Thanks!

**Comment by mefiu** [comment]
I'm pretty well familiar with git workflow, but this repository does not allow me to push any new branch into.
It says: "remote: Permission to nikeyes/Mantis2Trello.git denied to mefiu".

**Comment by nikeyes** [comment]
Previously you create the branch,  you need Fork the repository.

**Comment by Isarayzer** [comment]
Hi I'm from Brazil. I could not make the mantis work with trello, I'm using the latest mantis version "2.18.0". Should the "Mantis2Trello" folder be in which path in the mantis files? I'm using this path: /var/www/html/mantis/plugins.

**Comment by Isarayzer** [comment]
Hello, I'm from Brazil. I have the same problem, how I fix it problem? Someone can help me, please?

**Comment by nikeyes** [comment]
Hi Isarayzer,  Can you copy the url of your view.php of your mantis?  Thanks

**Comment by Isarayzer** [comment]
Hi nikeyes, thanks by your attention. Sorry I don't understand your question. Do you can explained with more details, please?

here is my URL https://mantis.stara.com.br/view.php

**Comment by nikeyes** [comment]
Hi  Isarayzer,  sorry for the delay.  I will make  a change tonight and publish a new version to support your Mantis url and fix the bug in my original code. 

Sorry for the inconvenience.

**Comment by nikeyes** [comment]
Hi! I publish a new version of the extension (0.3) in Chrome Web Store to support your Mantis Url.
Can you try with new version?

Check the version in Chrome Web Storage before update because in some countries google takes hours or days to deploy the versions.

![image](https://user-images.githubusercontent.com/5775194/48962536-7787ac80-ef81-11e8-9ec7-9a056d649d1f.png)

**Comment by Isarayzer** [comment]
Hello nikeyes. 

Wow, thanks so much it works to me. You the best. 
Thanks by your attention.
