### ISSUE TITLE
Trello does not request permission to access

### ISSUE THREAD

**Issue by renegustavo7** [nikeyes/Mantis2Trello#5]
Hi nikeyes,

Me and my team are trying to use this plugin, but when we click to create the card on Trello, he does not request permission to acess the cards. We try clean the cookies, change the manifest and background files, as another guy commented here, but unsuccesfully.

Do you have any idea what can it be or what can we do?

Regards.

**Comment by nikeyes** [comment]
Can you give me your Chrome version and Mantis version?  I will try to test with this versions. 

Thanks

**Comment by renegustavo7** [comment]
Hi, follows the versions:

Chrome: 70.0.3538.102
Mantis: 2.18.0

Thanks.

**Comment by nikeyes** [comment]
Hi renegustavo7,

Sorry for the delay.
Can you try to remove the "trello_token" from your Local Storage?
In Chrome you need to open developer tools (with F12) and got to Application Tab -> On the Left go to Local Storage and select your Mantis Url and remove key "trello_token"

![image](https://user-images.githubusercontent.com/5775194/48962213-27a6e680-ef7d-11e8-84a2-674e8e5a113c.png)

When you remove this key, the Extension ask you for new Credentials.

**Comment by renegustavo7** [comment]
Hello nikeyes,

Thanks for your reply. After your last update fixing the another issue commented by Isarayzer, Trello is now requesting authorization and working fine.

Thank you very much.

Regards.
